# Input configuration
input:
  supported_sources:
    - local
    - github
    - gitlab
  default_source: local

# Path configuration
paths:
  input:
    base_dir: .  # Use the current directory by default
    github: ""   # Default GitHub repository
    gitlab: ""   # Default GitLab repository
  output:
    base_dir: output  # Output base directory
    reports: reports  # Report directory
    trees: trees      # Directory tree file
    temp: temp        # Temporary file

# Tree structure configuration
tree:
  max_depth: 4 # Maximum depth of directory tree

# File configuration
file:
  max_size: 10485760  # 10MB
  encoding: utf-8     # File encoding

# Output configuration
output:
  formats:
    - md
    - json
    - txt
  default_format: md
  files:
    md: analysis_report.md
    json: analysis_report.json
    txt: analysis_report.txt
    tree: directory_tree.txt

# Content configuration
content:
  preview_length: 1000 # Content preview length (number of characters)
