version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - GITINGEST_S3_BUCKET=${GITINGEST_S3_BUCKET}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - GITHUB_PAT=${GITHUB_PAT}
       # (other existing env vars)
    volumes:
      - ./src:/app  # Optional: Mount source code for development 