name: Documentation

on:
  push:
    branches: [main]
    paths:
      - '**/*.md'
      - 'docs/**'
      - '.github/workflows/docs.yml'
  pull_request:
    branches: [main]
    paths:
      - '**/*.md'
      - 'docs/**'
      - '.github/workflows/docs.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install markdownlint-cli
        run: npm install -g markdownlint-cli

      - name: Lint markdown files
        run: markdownlint '**/*.md' --ignore node_modules --ignore .git

      - name: Check for broken links (if docs exist)
        if: hashFiles('docs/**') != ''
        run: |
          # Install markdown-link-check
          npm install -g markdown-link-check
          
          # Check links in all markdown files
          find . -name "*.md" -not -path "./node_modules/*" -not -path "./.git/*" | \
          xargs -I {} markdown-link-check {} --config .github/markdown-link-check-config.json || true

  check-spelling:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Check spelling
        uses: crate-ci/typos@v1.16.26
        with:
          files: '*.md docs/'
          isolated: false